# intents_data.py

intents = {
    "get_date": [
        "Wie ist das Datum?",
        "Sag mir das heutige Datum",
        "Heute ist welcher Tag?",
        "Welches Datum haben wir heute?",
        "Kannst du mir das Datum nennen?",
        "Was ist das heutige Datum?",
        "Datum bitte",
        "Heutiges Datum",
        "Welcher Tag ist heute?",
        "Welches Datum ist heute?",
        "Was für ein Datum haben wir heute?",
        "Gib mir das aktuelle Datum",
        "Wie lautet das heutige Datum?",
        "Heute ist das Datum?",
        "Nenne mir das Datum von heute",
        "Was ist das Datum heute?",
        "Heutiges Datum bitte",
        "Sag mir das Datum",
        "Datum für heute",
        "Welcher Tag ist es heute?",
        "Heutiger Tag",
        "Welcher Tag haben wir heute?",
        "Was ist das heutige Datum?",
        "Kannst du mir das aktuelle Datum sagen?",
        "Sag mir das Datum von heute",
        "Wie ist der heutige Tag?",
        "Welcher Tag ist heute?",
        "Was ist der heutige Tag?",
        "Sag mir den heutigen Tag",
        "Heute ist welcher Tag?",
        "Wie lautet das Datum heute?",
        "Was ist das heutige Datum?",
        "Heute haben wir welches Datum?",
        "Welcher Tag und welches Datum haben wir heute?",
        "Erzähl mir das heutige Datum",
        "Bitte nenne mir das heutige Datum",
        "Wie ist das heutige Datum?",
        "Was für ein Datum ist heute?",
        "Gib mir das heutige Datum",
        "Was ist das aktuelle Datum heute?",
        "Kannst du das Datum von heute nennen?",
        "Erzähl mir den heutigen Tag und das Datum",
        "Sag mir den heutigen Tag und das Datum",
        "Wie ist der heutige Tag und das Datum?"
    ],
    "get_time": [
        "Wie spät ist es?",
        "Sag mir die Uhrzeit",
        "Wie viel Uhr ist es?",
        "Welche Uhrzeit ist es jetzt?",
        "Kannst du mir die Uhrzeit sagen?",
        "Uhrzeit bitte",
        "Es ist wie viel Uhr?",
        "Aktuelle Uhrzeit",
        "Was ist die Zeit?",
        "Zeit bitte",
        "Wie ist die aktuelle Uhrzeit?",
        "Wie spät haben wir jetzt?",
        "Gib mir die aktuelle Uhrzeit",
        "Wie viel Uhr ist es momentan?",
        "Sag mir, wie spät es ist",
        "Was für eine Uhrzeit ist es?",
        "Heutige Uhrzeit",
        "Momentane Uhrzeit bitte",
        "Uhrzeit jetzt",
        "Wie ist die Zeit?",
        "Wie spät ist es gerade?",
        "Welche Zeit ist es?",
        "Was ist die aktuelle Uhrzeit?",
        "Sag mir die jetzige Uhrzeit",
        "Wie ist die Zeit jetzt?",
        "Gib mir die Uhrzeit",
        "Was ist die Uhrzeit?",
        "Sag mir die aktuelle Uhrzeit",
        "Was ist die momentane Uhrzeit?",
        "Wie viel Uhr haben wir jetzt?",
        "Bitte gib mir die Uhrzeit",
        "Wie ist die jetzige Uhrzeit?",
        "Wie viel Uhr ist es gerade?",
        "Sag mir die Zeit jetzt",
        "Was ist die momentane Zeit?",
        "Gib mir die Zeit",
        "Wie viel Uhr ist es heute?",
        "Wie spät ist es heute?",
        "Was ist die aktuelle Zeit?",
        "Sag mir die aktuelle Uhrzeit",
        "Wie viel Uhr ist es jetzt?",
        "Was ist die momentane Uhrzeit?",
        "Wie ist die Uhrzeit heute?",
        "Gib mir die jetzige Uhrzeit",
        "Wie viel Uhr ist es zu diesem Zeitpunkt?"
    ],
    "tell_joke": [
        "Erzähl mir einen Witz",
        "Kannst du einen Witz machen?",
        "Ich möchte einen Witz hören",
        "Bitte erzähl einen Witz",
        "Hast du einen guten Witz?",
        "Erzähl einen lustigen Witz",
        "Gib mir einen Witz",
        "Witz bitte",
        "Kannst du mir einen Witz erzählen?",
        "Ich brauche einen Witz",
        "Erzähl mir einen lustigen Witz",
        "Kennst du einen Witz?",
        "Ich möchte einen lustigen Witz hören",
        "Bitte mach einen Witz",
        "Witz erzähl bitte",
        "Erzähl einen kurzen Witz",
        "Ich will einen Witz hören",
        "Erzähl mir etwas Lustiges",
        "Bring mich zum Lachen mit einem Witz",
        "Witz erzählen",
        "Kannst du einen lustigen Witz erzählen?",
        "Ich möchte lachen, erzähl einen Witz",
        "Erzähl mir einen Witz",
        "Gib mir einen lustigen Witz",
        "Hör zu, erzähl einen Witz",
        "Bitte erzähl mir einen Witz",
        "Kannst du einen kurzen Witz machen?",
        "Ich brauche etwas zum Lachen, erzähl einen Witz",
        "Erzähl einen spaßigen Witz",
        "Hast du einen lustigen Witz für mich?",
        "Bring mich zum Schmunzeln mit einem Witz",
        "Ich möchte lachen, bitte erzähl einen Witz",
        "Erzähl mir etwas Lustiges",
        "Sag mir einen Witz",
        "Lass mich lachen, erzähl einen Witz",
        "Erzähl einen guten Witz",
        "Ich möchte einen lustigen Witz hören",
        "Bitte erzähl mir einen kurzen Witz",
        "Kannst du einen Witz erzählen?",
        "Ich möchte einen Witz hören, bitte"
    ],
    "get_weather": [
        "Wie ist das Wetter?",
        "Sag mir das aktuelle Wetter",
        "Wie ist das Wetter heute?",
        "Was ist das Wetter jetzt?",
        "Wie wird das Wetter?",
        "Wettervorhersage bitte",
        "Gib mir das Wetter",
        "Wie sieht das Wetter aus?",
        "Wetterbericht bitte",
        "Ist es heute sonnig?",
        "Wie ist die Wetterlage?",
        "Was für ein Wetter haben wir heute?",
        "Gibt es Regen heute?",
        "Wie wird das Wetter morgen?",
        "Wird es heute regnen?",
        "Ist das Wetter gut heute?",
        "Wie kalt ist es heute?",
        "Wie warm ist es heute?",
        "Erzähl mir vom Wetter",
        "Wetter update bitte",
        "Wie ist die Temperatur heute?",
        "Wird es heute bewölkt?",
        "Gibt es heute Sturm?",
        "Wie sonnig ist es heute?",
        "Erzähl mir die Wettervorhersage",
        "Was ist das Wetter für heute?",
        "Wie wird das Wetter in Berlin heute?",
        "Was für ein Wetter ist heute?",
        "Gibt es heute Schnee?",
        "Wie ist die Wetterprognose",
        "Sag mir die Wetterlage",
        "Wie wird das Wetter in den nächsten Tagen?",
        "Was erwartet uns das Wetter heute?",
        "Wie ist das Wetter in München?",
        "Wird es heute bewölkt?",
        "Wie viel Regen wird es heute geben?",
        "Ist es heute warm?",
        "Wie ist die Luftfeuchtigkeit heute?",
        "Wird es heute windig sein?",
        "Wie sieht die Wetterprognose aus?",
        "Was ist das aktuelle Wetter?"
    ],
    "exit": [
        "Beenden",
        "Schließe das Programm",
        "Stop",
        "Beende den Assistenten",
        "Programm beenden",
        "Assistent stoppen",
        "Verlasse die Anwendung",
        "Schließen bitte",
        "Ende",
        "Beende die Anwendung",
        "Assistenz beenden",
        "Programm schließen",
        "Stoppe das Programm",
        "Assistent beenden",
        "Beende das Programm",
        "Programm stoppen",
        "Schließe die Anwendung",
        "Stopp bitte",
        "Verlasse das Programm",
        "Ende bitte",
        "Bitte beende das Programm",
        "Beende bitte den Assistenten",
        "Schließe bitte das Programm",
        "Stoppe bitte den Assistenten",
        "Beende bitte die Anwendung",
        "Ende des Programms",
        "Beende den Assistenten bitte",
        "Schließe das Programm bitte",
        "Stopp das Programm",
        "Beende das Programm jetzt",
        "Programm beenden bitte",
        "Beende die Anwendung bitte",
        "Stoppe das Programm jetzt",
        "Ende jetzt",
        "Schalte jetzt das Programm",
        "Beende das Programm sofort",
        "Programm sofort beenden",
        "Beende den Assistenten sofort",
        "Schließe das Programm sofort",
        "Stopp jetzt das Programm",
        "Beende den Assistenten jetzt"
    ],
    "unknown": [
        "hey",
        "hallo",
        "hi",
        "guten Tag",
        "guten Morgen",
        "guten Abend",
        "servus",
        "salü",
        "hola",
        "bonjour",
        "wie geht's",
        "was machst du",
        "wie heißt du",
        "wer bist du",
        "was kannst du",
        "was ist dein Name",
        "wie war dein Tag",
        "hallo Assistent",
        "hi Assistent",
        "guten Nachmittag",
        "servus Assistent",
        "salü Assistent",
        "hola Assistent",
        "bonjour Assistent",
        "wie geht es dir",
        "was machst du gerade",
        "wie bist du",
        "wer ist du",
        "was kannst du alles",
        "wie heißt du Assistent",
        "wer bist du Assistent",
        "was ist dein Name Assistent",
        "wie war dein Tag heute",
        "hallo mein Assistent",
        "hi mein Assistent",
        "guten Tag mein Assistent",
        "guten Morgen mein Assistent",
        "guten Abend mein Assistent",
        "hallo HomeAI",
        "hi HomeAI",
        "hallo HomeAI Assistent",
        "guten Nachmittag HomeAI",
        "servus HomeAI",
        "salü HomeAI",
        "hola HomeAI",
        "bonjour HomeAI",
        "wie geht's HomeAI",
        "was machst du HomeAI",
        "wie heißt du HomeAI",
        "wer bist du HomeAI",
        "was kannst du HomeAI",
        "was ist dein Name HomeAI",
        "wie war dein Tag HomeAI",
        "hallo mein HomeAI",
        "hi mein HomeAI",
        "guten Tag mein HomeAI",
        "guten Morgen mein HomeAI",
        "guten Abend mein HomeAI",
        "hallo HomeAI Assistent",
        "hi HomeAI Assistent",
        "guten Nachmittag HomeAI Assistent",
        "servus HomeAI Assistent",
        "salü HomeAI Assistent",
        "hola HomeAI Assistent",
        "bonjour HomeAI Assistent",
        "wie geht's HomeAI Assistent",
        "was machst du HomeAI Assistent",
        "wie heißt du HomeAI Assistent",
        "wer bist du HomeAI Assistent",
        "was kannst du HomeAI Assistent",
        "was ist dein Name HomeAI Assistent",
        "wie war dein Tag HomeAI Assistent",
        "hallo mein HomeAI Assistent",
        "hi mein HomeAI Assistent",
        "guten Tag mein HomeAI Assistent",
        "guten Morgen mein HomeAI Assistent",
        "guten Abend mein HomeAI Assistent",
        "hallo mein HomeAI Assistent",
        "hi mein HomeAI Assistent"
    ],
    "control_device_on": [
        "Schalte die {device} ein",
        "Schalte den {device} ein",
        "Schalte das {device} ein",
        "Mach die {device} an",
        "Mach den {device} an",
        "Mach das {device} an",
        "Setze die {device} in Betrieb",
        "Setze den {device} in Betrieb",
        "Setze das {device} in Betrieb",
        "Aktiviere die {device}",
        "Aktiviere den {device}",
        "Aktiviere das {device}",
        "Starte die {device}",
        "Starte den {device}",
        "Starte das {device}",
        "Bitte schalte die {device} ein",
        "Bitte schalte den {device} ein",
        "Bitte schalte das {device} ein",
        "Bitte mach die {device} an",
        "Bitte mach den {device} an",
        "Bitte mach das {device} an",
        "Bitte setze die {device} in Betrieb",
        "Bitte setze den {device} in Betrieb",
        "Bitte setze das {device} in Betrieb",
        "Bitte aktiviere die {device}",
        "Bitte aktiviere den {device}",
        "Bitte aktiviere das {device}",
        "Bitte starte die {device}",
        "Bitte starte den {device}",
        "Bitte starte das {device}",
        "Schalte jetzt die {device} ein",
        "Schalte jetzt den {device} ein",
        "Schalte jetzt das {device} ein",
        "Mach jetzt die {device} an",
        "Mach jetzt den {device} an",
        "Mach jetzt das {device} an",
        "Aktiviere jetzt die {device}",
        "Aktiviere jetzt den {device}",
        "Aktiviere jetzt das {device}",
        "Starte jetzt die {device}",
        "Starte jetzt den {device}",
        "Starte jetzt das {device}"
    ],
    "control_device_off": [
        "Schalte die {device} aus",
        "Schalte den {device} aus",
        "Schalte das {device} aus",
        "Mach die {device} aus",
        "Mach den {device} aus",
        "Mach das {device} aus",
        "Setze die {device} außer Betrieb",
        "Setze den {device} außer Betrieb",
        "Setze das {device} außer Betrieb",
        "Deaktiviere die {device}",
        "Deaktiviere den {device}",
        "Deaktiviere das {device}",
        "Stoppe die {device}",
        "Stoppe den {device}",
        "Stoppe das {device}",
        "Bitte schalte die {device} aus",
        "Bitte schalte den {device} aus",
        "Bitte schalte das {device} aus",
        "Bitte mach die {device} aus",
        "Bitte mach den {device} aus",
        "Bitte mach das {device} aus",
        "Bitte setze die {device} außer Betrieb",
        "Bitte setze den {device} außer Betrieb",
        "Bitte setze das {device} außer Betrieb",
        "Bitte deaktiviere die {device}",
        "Bitte deaktiviere den {device}",
        "Bitte deaktiviere das {device}",
        "Bitte stoppe die {device}",
        "Bitte stoppe den {device}",
        "Bitte stoppe das {device}",
        "Schalte jetzt die {device} aus",
        "Schalte jetzt den {device} aus",
        "Schalte jetzt das {device} aus",
        "Mach jetzt die {device} aus",
        "Mach jetzt den {device} aus",
        "Mach jetzt das {device} aus",
        "Deaktiviere jetzt die {device}",
        "Deaktiviere jetzt den {device}",
        "Deaktiviere jetzt das {device}",
        "Stoppe jetzt die {device}",
        "Stoppe jetzt den {device}",
        "Stoppe jetzt das {device}"
    ],
    
    "special_ask": [
        "Ich habe eine Frage",
        "Ich hätte gerne eine Frage",
        "Darf ich etwas fragen",
        "Kann ich dich etwas fragen",
        "Ich möchte eine Frage stellen",
        "Ich möchte dich gerne etwas fragen",
        "Ich würde gerne eine Frage stellen",
        "Ich habe da mal eine Frage",
        "Ich habe eine wichtige Frage",
        "Ich hätte eine dringende Frage",
        "Darf ich dir eine Frage stellen",
        "Ich habe eine kurze Frage",
        "Ich wollte dich kurz etwas fragen",
        "Darf ich kurz nachfragen",
        "Ich hätte da mal was zu fragen",
        "Könnte ich kurz etwas fragen",
        "Ich benötige bitte eine Auskunft",
        "Ich wüsste gerne etwas",
        "Ich habe da noch eine Frage",
        "Ich brauche kurz deinen Rat",
        "Könntest du mir eine Frage beantworten",
        "Ich habe ein paar Unklarheiten",
        "Ich würde gerne etwas erfragen",
        "Ich brauche mal eine Information",
        "Lass mich dich etwas fragen",
        "Ich habe eine spezielle Frage",
        "Ich möchte deine Meinung zu etwas hören",
        "Ich benötige kurz deine Hilfe bei einer Frage",
        "Ich bin mir nicht sicher und wollte dich fragen",
        "Darf ich dich etwas zu einem bestimmten Thema fragen"
    ],
    
    "get_todays_events": [
        "Was sind meine heutigen Termine?",
        "Welche Termine habe ich heute?",
        "Zeig mir meine Termine für heute",
        "Welche Veranstaltungen habe ich heute?",
        "Was steht heute in meinem Kalender?",
        "Was ist mein Terminplan für heute?",
        "Habe ich heute irgendwelche Meetings?",
        "Was habe ich heute geplant?",
        "Zeig mir bitte meinen Kalender für heute",
        "Welche Verpflichtungen habe ich heute?",
        "Gibt es heute noch wichtige Termine?",
        "Kannst du mir meinen heutigen Tagesablauf anzeigen?",
        "Was ist heute alles geplant?",
        "Was steht heute an?",
        "Zeig mir meine Agenda für heute",
        "Was sind meine To-Dos für heute?",
        "Welche Aufgaben habe ich heute?",
        "Bitte liste meine heutigen Termine auf",
        "Wie sieht mein heutiger Zeitplan aus?",
        "Was habe ich heute noch vor?",
        "Kannst du meinen Kalender für den heutigen Tag abrufen?",
        "Zeig mir bitte alle heutigen Ereignisse",
        "Welche Events habe ich heute?",
        "Welche Meetings stehen heute an?",
        "Sind heute Besprechungen eingetragen?",
        "Habe ich heute Kundentermine?",
        "Was ist mein heutiger Stundenplan?",
        "Erzähle mir von meinen Terminen heute",
        "Was sollte ich heute nicht verpassen?",
        "Gibt es heute etwas Dringendes zu erledigen?",
        "Habe ich heute Fristen oder Deadlines?",
        "Wie sieht mein heutiges Programm aus?",
        "Sind heute bestimmte Anlässe oder Jubiläen?",
        "Gibt es heute Feierlichkeiten oder Geburtstage?",
        "Was sind meine heutigen Erinnerungen?",
        "Kannst du meine heutigen Aufgaben durchgehen?",
        "Welche Themen muss ich heute bearbeiten?",
        "Steht heute eine Reise oder ein Treffen an?",
        "Ist heute eine Veranstaltung, die ich besuchen muss?",
        "Kannst du mir alle heutigen Termine zusammenfassen?"
    ],
    "get_tomorrows_events": [
        "Was sind meine morgigen Termine?",
        "Welche Termine habe ich morgen?",
        "Zeig mir meine Termine für morgen",
        "Welche Veranstaltungen habe ich morgen?",
        "Was steht morgen in meinem Kalender?",
        "Habe ich morgen irgendwelche Meetings?",
        "Was ist mein Terminplan für morgen?",
        "Zeig mir bitte meinen Kalender für morgen",
        "Welche Verpflichtungen habe ich morgen?",
        "Wie sieht mein morgiger Tag aus?",
        "Gibt es morgen etwas Wichtiges?",
        "Kannst du mir meinen morgigen Tagesablauf anzeigen?",
        "Was ist morgen alles geplant?",
        "Was steht morgen an?",
        "Zeig mir meine Agenda für morgen",
        "Was sind meine To-Dos für morgen?",
        "Welche Aufgaben habe ich morgen?",
        "Bitte liste meine morgigen Termine auf",
        "Wie sieht mein morgiger Zeitplan aus?",
        "Was habe ich morgen vor?",
        "Kannst du meinen Kalender für den morgigen Tag abrufen?",
        "Zeig mir bitte alle morgigen Ereignisse",
        "Welche Events habe ich morgen?",
        "Welche Meetings stehen morgen an?",
        "Sind morgen Besprechungen eingetragen?",
        "Habe ich morgen Kundentermine?",
        "Was ist mein morgiger Stundenplan?",
        "Erzähle mir von meinen Terminen morgen",
        "Was sollte ich morgen nicht verpassen?",
        "Gibt es morgen etwas Dringendes zu erledigen?",
        "Habe ich morgen Fristen oder Deadlines?",
        "Wie sieht mein morgiges Programm aus?",
        "Sind morgen bestimmte Anlässe oder Jubiläen?",
        "Gibt es morgen Feierlichkeiten oder Geburtstage?",
        "Was sind meine morgigen Erinnerungen?",
        "Kannst du meine morgigen Aufgaben durchgehen?",
        "Welche Themen muss ich morgen bearbeiten?",
        "Steht morgen eine Reise oder ein Treffen an?",
        "Ist morgen eine Veranstaltung, die ich besuchen muss?",
        "Kannst du mir alle morgigen Termine zusammenfassen?"
    ]
}



